package tw.com.lixin.wm_casino.global;


import tw.com.lixin.wm_casino.R;

public class Poker {
    public static final int NUM(int no) {
        switch (no) {
            case 1:
                return R.drawable.poker_c1;
            case 2:
                return R.drawable.poker_c2;
            case 3:
                return R.drawable.poker_c3;
            case 4:
                return R.drawable.poker_c4;
            case 5:
                return R.drawable.poker_c5;
            case 6:
                return R.drawable.poker_c6;
            case 7:
                return R.drawable.poker_c7;
            case 8:
                return R.drawable.poker_c8;
            case 9:
                return R.drawable.poker_c9;
            case 10:
                return R.drawable.poker_c10;
            case 11:
                return R.drawable.poker_c11;
            case 12:
                return R.drawable.poker_c12;
            case 13:
                return R.drawable.poker_c13;
            case 21:
                return R.drawable.poker_d1;
            case 22:
                return R.drawable.poker_d2;
            case 23:
                return R.drawable.poker_d3;
            case 24:
                return R.drawable.poker_d4;
            case 25:
                return R.drawable.poker_d5;
            case 26:
                return R.drawable.poker_d6;
            case 27:
                return R.drawable.poker_d7;
            case 28:
                return R.drawable.poker_d8;
            case 29:
                return R.drawable.poker_d9;
            case 30:
                return R.drawable.poker_d10;
            case 31:
                return R.drawable.poker_d11;
            case 32:
                return R.drawable.poker_d12;
            case 33:
                return R.drawable.poker_d13;
            case 41:
                return R.drawable.poker_h1;
            case 42:
                return R.drawable.poker_h2;
            case 43:
                return R.drawable.poker_h3;
            case 44:
                return R.drawable.poker_h4;
            case 45:
                return R.drawable.poker_h5;
            case 46:
                return R.drawable.poker_h6;
            case 47:
                return R.drawable.poker_h7;
            case 48:
                return R.drawable.poker_h8;
            case 49:
                return R.drawable.poker_h9;
            case 50:
                return R.drawable.poker_h10;
            case 51:
                return R.drawable.poker_h11;
            case 52:
                return R.drawable.poker_h12;
            case 53:
                return R.drawable.poker_h13;
            case 61:
                return R.drawable.poker_s1;
            case 62:
                return R.drawable.poker_s2;
            case 63:
                return R.drawable.poker_s3;
            case 64:
                return R.drawable.poker_s4;
            case 65:
                return R.drawable.poker_s5;
            case 66:
                return R.drawable.poker_s6;
            case 67:
                return R.drawable.poker_s7;
            case 68:
                return R.drawable.poker_s8;
            case 69:
                return R.drawable.poker_s9;
            case 70:
                return R.drawable.poker_s10;
            case 71:
                return R.drawable.poker_s11;
            case 72:
                return R.drawable.poker_s12;
            case 73:
                return R.drawable.poker_s13;
            default:
                return 0;
        }
    }
}
